### ISSUE TITLE
Unable to compile the code 

### ISSUE THREAD

**Issue by TendsToInfinity** [h-hub/aws-cognito-spring#1]
Hi, I have attached Error logs for the same.
[ErrorLogs.txt](https://github.com/h-hub/aws-cognito-spring/files/4356081/ErrorLogs.txt)
)

I am trying doing mvn install to build an executable jar  but it's throwing the below error

Caused by: java.lang.IllegalArgumentException: invalid target release: 11

I am new to this, so please if you can help with this?

**Comment by h-hub** [comment]
For this, you have to use java 11.

If you are using eclipse, change the version from settings.

If you are running a maven install from the CMD/terminal, change the java version in the system, using environmental variables.

More info: https://stackoverflow.com/questions/51468580/maven-invalid-target-release-10

Hope this helps, if not, please let me know.

**Comment by TendsToInfinity** [comment]
**ya after using JAVA 11, was able to get a success ful build 
but while running jar got the below error**
============================================================
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/harshakj/cognitoDemo/CognitoDemoApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

**Comment by TendsToInfinity** [comment]
Thanks for the help man!
I just removed java 11, using java 1.8 and its working, just facing few issues with the AWS login, will let you in case of any other difficulties

**Comment by h-hub** [comment]
happy to help
